version: '3.3'

configs:
  traefik_config:
    file: ./traefik/config.toml

services:
  reverse-proxy:
    image: traefik
    networks:
      - southeast
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
    ports:
      - target: 80
        protocol: tcp
        published: 80
        mode: ingress
      - target: 8080
        protocol: tcp
        published: 8080
        mode: ingress
    configs:
    - source: traefik_config
      target: /etc/traefik/traefik.toml
      mode: 444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  southeast:
    external: true
