version: '3.3'

services:
  agent:
    image: portainer/agent
    networks:
      - southeast
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

  portainer:
    image: portainer/portainer
    networks:
      - southeast
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=southeast"
        - "traefik.frontend.rule=Host:portainer.traefik"
      placement:
        constraints: [node.role == manager]

volumes:
  portainer-data:
    external: true

networks:
  southeast:
    external: true
