logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[ping]
entryPoint = "http"

[api]
entryPoint = "traefik"
dashboard = true

[docker]
domain = "traefik"
watch = true
swarmMode = true
exposedByDefault = false
